apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-configmap
  namespace: wp
data:
  WORDPRESS_DB_HOST: "db-service.db.svc.cluster.local"    
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"

---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: "d29yZHByZXNz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wp
spec:
  selector:
    matchLabels:
      id: c0924469          # Pod label to be used by Service to select the pods from this deployment
  replicas: 3              # number of replica of the Pods
  template:
    metadata:
      labels:
        id: c0924469
        app: wp-app
        env: dev
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest      # which image it will use
        ports:
        - containerPort: 80 
        envFrom:
          - configMapRef:
              name: wp-configmap
              optional: false
          - secretRef:
              name: wp-secret
              optional: false   
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wp
  labels:
    version: v1      # label of the service
spec:
  type: ClusterIP
  ports:
  - port: 80        # the port on which the service is listening
    protocol: TCP
    targetPort: 80     # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    id: c0924469      # Pod label that service is using to select Pods

---
